OUTCOME = ['LEAK', 'CLOT']

CATEGORICAL_PRE = [
    'SEX', 'race_PUF', 'hispanic', 'CPT', 'GERD', 'MOBILITY_DEVICE',
    'HISTORY_DVT', 'MI_ALL_HISTORY', 'PTC', 'PCARD', 'HIP', 'HTN_MEDS',
    'HYPERLIPIDEMIA', 'VENOUS_STASIS', 'DIALYSIS', 'RENAL_INSUFFICIENCY',
    'THERAPEUTIC_ANTICOAGULATION', 'DIABETES', 'SMOKER',
    'FUNSTATPRESURG', 'COPD', 'OXYGEN_DEPENDENT', 'HISTORY_PE', 'SLEEP_APNEA',
    'CHRONIC_STEROIDS', 'IVCF', 'ASACLASS', 'ASSISTANT_TRAINING_LEVEL',
    'OPYEAR',
]

CONTINUOUS_PRE = [
    'HGTCM', 'BMI_CONSOL', 'BMI_DELTA', 'WGTKG', 'AGE_CONSOL', 'ALBUMIN', 'HCT',
]

CONTINUOUS_POST = ['OPLENGTH']

CATEGORICAL_ORDER = {
    'SEX': ['Unknown','Female', 'Male'],
    'race_PUF': [
        'Unknown/Not Reported', 'Black or African American',
        'American Indian or Alaska Native', 'White',
        'Native Hawaiian or Other Pacific Islander', 'Asian'
    ],
    'hispanic': ['Unknown', 'No', 'Yes'],
    'CPT': ['Unknown',43775, 43644],
    'GERD': ['Unknown','No', 'Yes'],
    'MOBILITY_DEVICE': ['Unknown','No', 'Yes'],
    'HISTORY_DVT': ['Unknown','No', 'Yes'],
    'MI_ALL_HISTORY': ['Unknown','No', 'Yes'],
    'PTC': ['Unknown','No', 'Yes'],
    'PCARD': ['Unknown','No', 'Yes'],
    'HIP': ['Unknown','No', 'Yes'],
    'HTN_MEDS': ['Unknown','0', '2', '3+', '1'],
    'HYPERLIPIDEMIA': ['Unknown','No', 'Yes'],
    'VENOUS_STASIS': ['Unknown','No', 'Yes'],
    'DIALYSIS': ['Unknown','No', 'Yes'],
    'RENAL_INSUFFICIENCY': ['Unknown','No', 'Yes'],
    'THERAPEUTIC_ANTICOAGULATION': ['Unknown','No', 'Yes'],
    'PREVIOUS_SURGERY': ['Unknown','No', 'Yes'],
    'DIABETES': ['Unknown','No', 'Non-Insulin', 'Insulin'],
    'SMOKER': ['Unknown','No', 'Yes'],
    'FUNSTATPRESURG': [
        'Unknown','Independent', 'Partially Dependent', 'Totally Dependent'
    ],
    'COPD': ['Unknown','No', 'Yes'],
    'OXYGEN_DEPENDENT': ['Unknown','No', 'Yes'],
    'HISTORY_PE': ['Unknown','No', 'Yes'],
    'SLEEP_APNEA': ['Unknown','No', 'Yes'],
    'CHRONIC_STEROIDS': ['Unknown','No', 'Yes'],
    'IVCF': [
        'Unknown', 'No', 'IVC filter was pre-existing',
        'IVC filter placed in anticipation of the metabolic or bariatric procedure'
    ],
    'ASACLASS': [
        'Unknown', '3-Severe Disturb', '2-Mild Disturb', '1-No Disturb',
        '4-Life Threat', '5-Moribund'
    ],
    'ASSISTANT_TRAINING_LEVEL': [
        'None (no assist or scrub tech/RN only)',
        'Physician Assistant/Nurse Practitioner/Registered Nurse First Assist',
        'Resident (PGY 1-5+)', 'Minimally Invasive Surgery Fellow',
        'Attending - Other', 'Attending - Weight Loss Surgeon'
    ],
    'OPYEAR': [2015, 2016, 2017],
    'HYPOALB': [
        0,
        1,
        2,
    ],
    'ANEMIA': [0, 1, 2]
}


REF_CATS = {'SEX_0': 'Unknown',
 'SEX_1': 'Female.',
 'SEX_2': 'Male',
 'race_PUF_0': 'Unknown/Not Reported',
 'race_PUF_1': 'Black or African American',
 'race_PUF_2': 'American Indian or Alaska Native',
 'race_PUF_3': 'White.',
 'race_PUF_4': 'Native Hawaiian or Other Pacific Islander',
 'race_PUF_5': 'Asian',
 'hispanic_0': 'Unknown',
 'hispanic_1': 'No.',
 'hispanic_2': 'Yes',
 'CPT_0': 'Unknown',
 'CPT_1': '43775.',
 'CPT_2': '43644',
 'GERD_0': 'Unknown',
 'GERD_1': 'No.',
 'GERD_2': 'Yes',
 'MOBILITY_DEVICE_0': 'Unknown',
 'MOBILITY_DEVICE_1': 'No.',
 'MOBILITY_DEVICE_2': 'Yes',
 'HISTORY_DVT_0': 'Unknown',
 'HISTORY_DVT_1': 'No.',
 'HISTORY_DVT_2': 'Yes',
 'MI_ALL_HISTORY_0': 'Unknown',
 'MI_ALL_HISTORY_1': 'No.',
 'MI_ALL_HISTORY_2': 'Yes',
 'PTC_0': 'Unknown',
 'PTC_1': 'No.',
 'PTC_2': 'Yes',
 'PCARD_0': 'Unknown',
 'PCARD_1': 'No.',
 'PCARD_2': 'Yes',
 'HIP_0': 'Unknown',
 'HIP_1': 'No.',
 'HIP_2': 'Yes',
 'HTN_MEDS_0': 'Unknown',
 'HTN_MEDS_1': '0.',
 'HTN_MEDS_2': '2',
 'HTN_MEDS_3': '3+',
 'HTN_MEDS_4': '1',
 'HYPERLIPIDEMIA_0': 'Unknown',
 'HYPERLIPIDEMIA_1': 'No.',
 'HYPERLIPIDEMIA_2': 'Yes',
 'VENOUS_STASIS_0': 'Unknown',
 'VENOUS_STASIS_1': 'No.',
 'VENOUS_STASIS_2': 'Yes',
 'DIALYSIS_0': 'Unknown',
 'DIALYSIS_1': 'No.',
 'DIALYSIS_2': 'Yes',
 'RENAL_INSUFFICIENCY_0': 'Unknown',
 'RENAL_INSUFFICIENCY_1': 'No.',
 'RENAL_INSUFFICIENCY_2': 'Yes',
 'THERAPEUTIC_ANTICOAGULATION_0': 'Unknown',
 'THERAPEUTIC_ANTICOAGULATION_1': 'No.',
 'THERAPEUTIC_ANTICOAGULATION_2': 'Yes',
 'DIABETES_0': 'Unknown',
 'DIABETES_1': 'No.',
 'DIABETES_2': 'Non-Insulin',
 'DIABETES_3': 'Insulin',
 'SMOKER_0': 'Unknown',
 'SMOKER_1': 'No.',
 'SMOKER_2': 'Yes',
 'FUNSTATPRESURG_0': 'Unknown',
 'FUNSTATPRESURG_1': 'Independent.',
 'FUNSTATPRESURG_2': 'Partially Dependent',
 'FUNSTATPRESURG_3': 'Totally Dependent',
 'COPD_0': 'Unknown',
 'COPD_1': 'No.',
 'COPD_2': 'Yes',
 'OXYGEN_DEPENDENT_0': 'Unknown',
 'OXYGEN_DEPENDENT_1': 'No.',
 'OXYGEN_DEPENDENT_2': 'Yes',
 'HISTORY_PE_0': 'Unknown',
 'HISTORY_PE_1': 'No.',
 'HISTORY_PE_2': 'Yes',
 'SLEEP_APNEA_0': 'Unknown',
 'SLEEP_APNEA_1': 'No.',
 'SLEEP_APNEA_2': 'Yes',
 'CHRONIC_STEROIDS_0': 'Unknown',
 'CHRONIC_STEROIDS_1': 'No.',
 'CHRONIC_STEROIDS_2': 'Yes',
 'IVCF_0': 'Unknown',
 'IVCF_1': 'No.',
 'IVCF_2': 'IVC filter was pre-existing',
 'IVCF_3': 'IVC filter placed in anticipation of the metabolic or bariatric procedure',
 'ASACLASS_0': 'Unknown',
 'ASACLASS_1': '3-Severe Disturb',
 'ASACLASS_2': '2-Mild Disturb',
 'ASACLASS_3': '1-No Disturb.',
 'ASACLASS_4': '4-Life Threat',
 'ASACLASS_5': '5-Moribund',
 'ASSISTANT_TRAINING_LEVEL_0': 'None (no assist or scrub tech/RN only)',
 'ASSISTANT_TRAINING_LEVEL_1': 'Physician Assistant/Nurse Practitioner/Registered Nurse First Assist',
 'ASSISTANT_TRAINING_LEVEL_2': 'Resident (PGY 1-5+).',
 'ASSISTANT_TRAINING_LEVEL_3': 'Minimally Invasive Surgery Fellow',
 'ASSISTANT_TRAINING_LEVEL_4': 'Attending - Other',
 'ASSISTANT_TRAINING_LEVEL_5': 'Attending - Weight Loss Surgeon',
 'OPYEAR_0': '2015.',
 'OPYEAR_1': '2016',
 'OPYEAR_2': '2017'}



